trigger:
  branches:
    include:
      - docker-container-testing

variables:
- group: bookshelf-api-secrets-aca

pool:
  vmImage: ubuntu-latest

stages:

# ==========================
# Build & Push Image
# ==========================
- stage: Build
  displayName: Build and Push Image

  jobs:
  - job: Build

    steps:

      - task: Docker@2
        displayName: Build and Push Web Image
        inputs:
          command: buildAndPush
          repository: bookshelf-api
          dockerfile: 'Dockerfile'
          containerRegistry: 'vn-sc-acr-bookshelf'
          tags: |
            latest
            $(Build.BuildId)

# ==========================
# Run Migrations
# ==========================
- stage: Migrate
  displayName: Run Database Migration

  dependsOn: Build

  jobs:
  - job: Migrate

    steps:

    - task: UseDotNet@2
      displayName: Install .NET SDK
      inputs:
        packageType: sdk
        version: '9.x'

    - script: |
        dotnet tool install --global dotnet-ef
        export PATH="$PATH:$HOME/.dotnet/tools"
      displayName: Install EF Tool

    - script: |
        echo "Value starts with:"

        echo "$ConnectionStrings__DefaultConnection"
        echo "$ConnectionStrings__DefaultConnection" | cut -c1-40
        echo "Connection string loaded successfully"
        echo "Length: ${#ConnectionStrings__DefaultConnection}"
        dotnet restore BookShelf.Api.csproj
        dotnet ef database update \
          --project BookShelf.Api.csproj \
          --startup-project BookShelf.Api.csproj
      displayName: Test Variables
      env:
        ConnectionStrings__DefaultConnection: 'Server=tcp:bookshelf.database.windows.net,1433;Initial Catalog=free-sql-db-3528898;Persist Security Info=False;User ID=YOUR_USER;Password=YOUR_PASSWORD;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;'
# ==========================
# Deploy ACA
# ==========================
- stage: Deploy
  displayName: Deploy to ACA

  dependsOn: Build

  jobs:
  - job: Deploy

    steps:

    - task: AzureCLI@2
      displayName: Deploy API ACA

      inputs:
        azureSubscription: 'Book-App-Connection'
        scriptType: pscore
        scriptLocation: inlineScript

        inlineScript: |
          az containerapp update `
            --name bookshelf-api-app `
            --resource-group rg-bookshelf-aca-dev `
            --image bookshelfacr2026.azurecr.io/bookshelf-api:$(Build.BuildId)