# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureWebApp@1
  inputs:
      azureSubscription: 'ME-MngEnvMCAP517100-v-parvkaur-1 (f1c89731-86b0-4cd4-bd2d-f2347c1d62d2)'
      appType: 'webAppLinux'
      appName: 'book-api'
      deployToSlotOrASE: true
      resourceGroupName: 'DevOps'
      slotName: 'staging'
      package: '$(System.DefaultWorkingDirectory)/**/*.zip'
      runtimeStack: 'DOTNETCORE|9.0'
