apiVersion: v1
kind: Service

metadata:
  name: bookshelf-api
  azure.workload.identity/use: "true"

spec:
  type: ClusterIP

  selector:
    app: bookshelf-api

  ports:
    - port: 8080
      targetPort: 8080
      