apiVersion: v1
kind: Secret

metadata:
  name: bookshelf-api-secret

type: Opaque

stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=BookShelfDb;User Id=sa;Password=YourTemporaryPassword123!;TrustServerCertificate=True"