apiVersion: v1
kind: Secret

metadata:
  name: bookshelf-api-secret
  namespace: bookshelf

type: Opaque

stringData:
  ConnectionStrings__DefaultConnection: "Server=tcp:bookshelf.database.windows.net,1433;Initial Catalog=free-sql-db-3528898;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication=Active Directory Managed Identity; User Id=47c623f3-7cca-4c5b-9032-93efb31b8127;"
  Jwt__Key: "ChangeThisDevelopmentOnlyJwtSigningKey12345!"
  # should refere these values in deploy