apiVersion: v1
kind: Secret

metadata:
  name: bookshelf-api-secret
  namespace: bookshelf

type: Opaque

stringData:
  ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=BookShelfDb;User Id=sa;Password=YourTemporaryPassword123!;TrustServerCertificate=True"
  Jwt__Key: "ChangeThisDevelopmentOnlyJwtSigningKey12345!"
  # should refere these values in deploy