apiVersion: v1
kind: ConfigMap
metadata:
  name: bookshelf-api-config
  namespace: bookshelf

data:
  Jwt__Issuer: "BookShelf.Api"
  Jwt__Audience: "BookShelf.Web"
  Jwt__ExpirationMinutes: "120"

  AzureStorage__AccountName: "csharpdq43cm"
  AzureStorage__ContainerName: "uploads"